### PR TITLE
fix: Allow getResolvedName to resolve QualifiedName in TraitUseClause

### PR DESCRIPTION
**Pull request by zobo**
Discussion in https://github.com/microsoft/tolerant-php-parser/issues/400

### CODE REVIEW

**Review by roblourens — COMMENTED** [review]
Thanks for the PR. The change is fine to me, but there are tests for this, so please update those too.

**Review by roblourens — COMMENTED** [review]
Thanks for the PR. The change is fine to me, but there are tests for this, so please update those too.

**Comment by zobo** [comment]
Ah, managed to miss those due to all the noise running phpunit on windows. Will look at those asap.

**Comment by zobo** [comment]
@microsoft-github-policy-service agree

**Review by roblourens — APPROVED** [review]

**Review by DonJayamanne — APPROVED** [review]

**Pull request merged**
