### PR TITLE
Fix #194 - oddities around the static keyword.

### LINKED ISSUE #194: `new static::$classNameA()` should not be an error
See https://github.com/felixfbecker/php-language-server/issues/482

### PR DESCRIPTION
**Pull request by MaartenStaa**
Previously, all of the following examples would produce parse errors,
while being valid PHP code:

- new static;
- new static::$a;
- if ($a instanceof static) {}

This commit takes care of these edge cases.

### CODE REVIEW

**Comment by MaartenStaa** [comment]
I added tests to the best of my ability, but I'm not super familiar with the code base, so any feedback is welcome. 😃

**Comment by jens1o** [comment]
Awesome! :)

**Comment by jens1o** [comment]
@felixfbecker Could you file a new release, please?

**Comment by roblourens** [comment]
v0.0.8 contains this

**Pull request merged**
