### PR TITLE
Add MissingToken for missing QualifiedName

### PR DESCRIPTION
**Pull request by TysonAndre**
And emit a diagnostic - these would be parse errors in php

### CODE REVIEW

**Comment by TysonAndre** [comment]
@roblourens - this is ready for review

**Comment by TysonAndre** [comment]
@roblourens - thoughts?

**Review by roblourens — APPROVED** [review]

**Comment by roblourens** [comment]
Thanks! Sorry for taking so long to get back to these.

**Comment by dantleech** [comment]
I think this causes a regression:

```
Fatal error: Uncaught TypeError: Microsoft\PhpParser\ResolvedName::buildName(): Argument #1 ($tokens) must be of type array, nul
l given, called in /home/daniel/www/phpactor/phpactor/vendor/microsoft/tolerant-php-parser/src/NamespacedNameTrait.php on line 35 and defined in /home/daniel/www/phpactor/phpactor/vendor/microsoft/tolerant-php-parser/src/ResolvedName.php:15
Stack trace:                                                                                                                    #0 /home/daniel/www/phpactor/phpactor/vendor/microsoft/tolerant-php-parser/src/NamespacedNameTrait.php(35): Microsoft\PhpParser\
ResolvedName::buildName()
```

i.e. 

```
        if ($namespaceDefinition->name !== null) {
            $resolvedName = ResolvedName::buildName($namespaceDefinition->name->nameParts, $content);
```

now tries to access `nameParts` on NULL.

**Pull request merged**
